# input batch size
batch_size: 192
# maximum label length
batch_max_length: 25
# number of data loading workers
workers: 0
# the height of the input image
imgH: 32
# the width of the input image
imgW: 100
# character label
character: '0123456789abcdefghijklmnopqrstuvwxyz'
sensitive: True

# Model Architecture
Transformation: 'TPS'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'Attn'

# number of fiducial points of TPS-STN
num_fiducial: 20
# the number of input channel of Feature extractor
input_channel: 1
# the number of output channel of Feature extractor
output_channel: 512
# the size of the LSTM hidden state
hidden_size: 256
PAD: False
