name: receipt-ocr
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
    - torch==1.9.1
    - torchvision==0.10.1
    - opencv-python==4.5.3.56
    - scikit-image==0.18.3
    - scipy==1.7.1
    - PyYAML==5.4.1
    - onnx==1.10.1
    - onnxruntime==1.9.0
    - fastapi==0.68.1
    - uvicorn[standard]
    - pydantic