# Generated by Django 3.2.8 on 2022-10-18 10:53

import cash_flow_management.apps.Rich_Mindset.models.Transaction_model
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rich_Mindset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Fashion', 'Fashion'), ('Health', 'Health'), ('FINANCE', 'Finance'), ('ASSET', 'Asset(car/house etc)'), ('OTHER', 'Other')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('expenditure', models.IntegerField(blank=True, null=True)),
                ('reciept', models.ImageField(blank=True, null=True, upload_to=cash_flow_management.apps.Rich_Mindset.models.Transaction_model.directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('expenditure__isnull', False), ('reciept__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
