# Generated by Django 3.2.8 on 2022-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rich_Mindset', '0003_transaction_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='not_both_null',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reciept',
            new_name='receipt',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('expenditure__isnull', False), ('receipt__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
